services:

  authservice:
    build:
      context: .
      dockerfile: .docker/Dockerfile.auth
    container_name: authservice
    network_mode: host
    ports:
      - "8081:8081"   
    restart: unless-stopped

  orderservice:
    build:
      context: .
      dockerfile: .docker/Dockerfile.order
    container_name: orderservice
    network_mode: host
    ports:
      - "8082:8082"   
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: .docker/Dockerfile.front
    container_name: frontend
    ports:
       - "4200:4200"
    restart: unless-stopped

  gateway:
    build:
      context: .
      dockerfile: .docker/Dockerfile.gateway
    container_name: gateway
    network_mode: host
    ports:
      - "8080:8080"  
    depends_on:
      - authservice
      - orderservice
    restart: unless-stopped
