spring:
  application:
    name: OrderService

  rabbitmq:
    host: rabbitmq        # nome do container no docker-compose
    port: 5672
    username: admin
    password: admin
    virtual-host: /

  datasource:
    url: jdbc:h2:mem:ordersdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
    hikari:
      maximum-pool-size: 5

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        dialect: org.hibernate.dialect.H2Dialect

server:
  port: 8082
  tomcat:
    accesslog:
      enabled=false:

jwt:
  public-key: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzavczcm5JNpqtxN+QFAu
    WNOPQDPLJyItYGQgTSexiCZykVIciFyl0O92vV+OOFgUpTcR2i76wqvK01yT3Fpn
    1Uv9eXCWOu6EcL+sXDlSgjbzKLCpFgoUSeHiXVZcxerpA3P0qXZ7ANKmM4GAmpHL
    pOLm5bIISOfcThiVZ/EpxtLf7bBKviuTifKZffskQRX3lutnAed6+0fs1XUix8b3
    y100JGTlRPvm93tb8mMzlmcZ68fbvBEczEf8Gd9QMjGIqSk5h9LC98AqN9RFIQVs
    pUGgH7bhxr4dIAJIakc/Ti5FPNlILmi/BVL2jNICTwlvGJXBg8CuzkVlB+27fvdc
    1QIDAQAB
    -----END PUBLIC KEY-----

logging:
  level:
    root: WARN

    org.springframework.boot.web.embedded.tomcat: INFO
    org.apache.catalina.startup: INFO
    org.hibernate.SQL: ERROR
    org.hibernate.orm.jdbc.bind: ERROR
    org.hibernate.type.descriptor.sql: ERROR
    org.hibernate.engine: ERROR
    org.hibernate.stat: ERROR
    org.hibernate.tool.hbm2ddl: ERROR
    org.springframework.jdbc.core: ERROR
    org.springframework.orm.jpa: ERROR

    com.zaxxer.hikari: ERROR
